"""Created album and songs

Revision ID: faeb13c142bf
Revises: 
Create Date: 2025-11-27 19:01:44.539050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faeb13c142bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('album_name', sa.String(), nullable=False),
                    sa.Column('image_url', sa.String(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('album_name'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('songs',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('song_name', sa.String(), nullable=True),
                    sa.Column('album_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )


def downgrade() -> None:
    op.drop_table('songs')
    op.drop_table('albums')

